max:
  cpus: 62 # cores
  ram: 30 # GB
  swap_size: 10 # GB
  gpus: 1

  shm_rate: ram / (ram + swap_size)
  memory: ram + swap_size

  backup_space: 200 # GB
  work_space: 500 # GB

allow_userIDs:
  -  #<user id>

max_default_capability:
  cpus: 8
  memory: 32
  gpus: 1

  backup_space: 50
  work_space: 200

max_custom_capability:
  # <user id>:
  #   cpus: max
  #   memory: 12
  #   gpus: max
  #   backup_space: max
  #   if there is not parameter, follow by max_default_capability
